# Change these first
owner: PowerfulRichard
repo: PT-Status
user-agent: PowerfulRichard
 
sites:
  - name: CHDBits
    check: "tcp-ping"
    url: $CHD
    port: 443
    maxResponseTime: 1000
  - name: Femdomcult
    check: "tcp-ping"
    url: $FDC
    port: 2710
    maxResponseTime: 1000
  - name: GreatPostWall(GPW)
    url: $GPW
    maxResponseTime: 1000
  - name: GT-Org
    url: $GTORG
    maxResponseTime: 1000
  - name: GTru
    url: $GTRU
    maxResponseTime: 1000
  - name: HDArea
    url: $HDAREA
    maxResponseTime: 1000
  - name: HDAtoms
    url: $HDATOMS
    maxResponseTime: 1000
  - name: HDFans
    url: $HDF
    maxResponseTime: 1000
  - name: KamePT
    check: "tcp-ping"
    url: $KAME
    port: 443
    maxResponseTime: 1000
  - name: M-Team
    url: $MT
    maxResponseTime: 1000
  - name: PT-Time
    check: "tcp-ping"
    url: $PTT
    port: 443
    maxResponseTime: 1000
  - name: TorrentLeech
    url: $TL
    maxResponseTime: 1000
    
status-website:
  workflowSchedule:
    uptime: "*/5 * * * *"
  baseUrl: /PT-Status
  logoUrl: https://upptime.js.org/img/icon.svg
  name: PT站状态监控 丨 Private Tracker Status Monitor
  introTitle: PT站状态监控 丨 Private Tracker Status Monitor
  introMessage: 基于Github Pages和Upptime的PT站监控 丨 Private Tracker Status Monitor based on Github Pages and Upptime
  theme: ocean
  navbar:
    - title: 状态监控
      href: /
    - title: GitHub
      href: https://github.com/powerfulrichard
