# Change these first
owner: PowerfulRichard # Your GitHub organization or username, where this repository lives
repo: PT-Status # The name of this repository

sites:
  - name: CHDBits
    url: $CHD
    maxResponseTime: 5000
  - name: Femdomcult
    url: $FDC
    maxResponseTime: 5000
  - name: GreatPostWall(GPW)
    url: $GPW
    maxResponseTime: 5000
  - name: GT-Org
    url: $GTORG
    maxResponseTime: 5000
  - name: GTru
    url: $GTRU
    maxResponseTime: 5000
  - name: Haidan
    url: $HAIDAN
    maxResponseTime: 5000
  - name: HDArea
    url: $HDAREA
    maxResponseTime: 5000
  - name: HDAtoms
    url: $HDATOMS
    maxResponseTime: 5000
  - name: HDFans
    url: $HDF
    maxResponseTime: 5000
  - name: HDZone
    url: $HDZ
    maxResponseTime: 5000
  - name: KamePT
    url: $KAME
    maxResponseTime: 5000
  - name: M-Team
    url: $MT
    maxResponseTime: 5000
  - name: PT-Time
    url: $PTT
    maxResponseTime: 5000
  - name: TorrentLeech
    url: $TL
    maxResponseTime: 5000
    
status-website:
  workflowSchedule:
    uptime: "*/5 * * * *"
  baseUrl: /PT-Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: PT站状态监控 | Private Tracker Status Monitor
  introTitle: PT站状态监控<br>Private Tracker Status Monitor
  introMessage:  基于Github Pages和Upptime的PT站监控<br>Private Tracker Status Monitor based on Github Pages and Upptime
  theme: ocean
  navbar:
    - title: 状态监控
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  activeIncidents: 当前离线网站
  allSystemsOperational: 所有网站正常运行
  incidentReport: "事件 #$NUMBER 报告 →"
  activeIncidentSummary: 在 $DATE 出现 $POSTS 个事件
  incidentTitle: 事件 $NUMBER 的详细信息
  incidentDetails: 事件详细信息
  incidentFixed: 已恢复访问
  incidentOngoing: 网站停机中
  incidentOpenedAt: 开始于
  incidentClosedAt: 结束于
  incidentSubscribe: 订阅更新
  incidentViewOnGitHub: 在 GitHub 上查看
  incidentCommentSummary: 由 $AUTHOR 在 $DATE 发布
  incidentBack: ← 返回所有事件
  pastIncidents: 过去的事件
  pastIncidentsResolved: $POSTS 个问题在 $MINUTES 分钟内得到解决
  liveStatus: 实时状态
  overallUptime: "总体正常运行时间： $UPTIME"
  overallUptimeTitle: 总体正常运行时间
  averageResponseTime: "平均响应时间: $TIMEms"
  averageResponseTimeTitle: 平均响应时间
  sevelDayResponseTime: 7 天响应时间
  responseTimeMs: 响应时间（毫秒）
  ms: 毫秒
  loading: 加载中
  navGitHub: GitHub
  footer: 
  rateLimitExceededTitle: 超出速率限制
  rateLimitExceededIntro: 您已超过一小时内可以执行的请求数，因此您必须等待才能再次访问此网站。或者，您可以添加 GitHub 个人访问令牌以继续使用本网站。
  rateLimitExceededWhatDoesErrorMean: 这个错误是什么意思？本网站使用 GitHub API 访问有关我们网站状态的实时数据。默认情况下，GitHub 允许每个 IP 地址每小时 60 个请求，您已经消耗了这些请求。
  rateLimitExceededErrorHowCanFix: 我该如何解决？
  rateLimitExceededErrorFix: 您可以再等一个小时，您的 IP 地址限制将恢复。或者，您可以添加您的 GitHub 个人访问令牌，这将为您提供每小时额外 5,000 个请求。
  rateLimitExceededGeneratePAT: 了解如何生成个人访问令牌
  rateLimitExceededHasSet: 您有一个个人访问令牌集。
  rateLimitExceededRemoveToken: 删除令牌
  rateLimitExceededGitHubPAT: GitHub 个人访问令牌
  rateLimitExceededCopyPastePAT: 复制并粘贴您的令牌
  rateLimitExceededSaveToken: 保存令牌
  errorTitle: 发生错误
  errorIntro: 尝试获取最新状态详细信息时出错。
  errorText: 您可以稍后再试。
  errorHome: 转到主页
  pastScheduledMaintenance: 历史定期维护
  scheduledMaintenance: 定期维护
  scheduledMaintenanceSummaryStarted: 从 $DATE 开始，持续 $DURATION 分钟
  scheduledMaintenanceSummaryStarts: 从 $DATE 开始，已经离线 $DURATION 分钟
  startedAt: 开始在
  startsAt: 开始于
  duration: 持续时间
  durationMin: $DURATION 分钟
  incidentCompleted: 已完成
  incidentScheduled: 已预定
  url: "链接"
  status: "状态"
  history: "历史"
  responseTime: "响应时间"
  uptime: "正常运行时间"
  up: "🟩 正常运行"
  degraded: "🟨 运行缓慢"
  down: "🟥 停机"
  responseTimeGraphAlt: "响应时间图像"
  responseTimeDay: "24 小时响应时间"
  responseTimeWeek: "7 天正常运行时间"
  responseTimeMonth: "30天的正常运行时间"
  responseTimeYear: "1年的正常运行时间"
  uptimeDay: "24 小时正常运行时间"
  uptimeWeek: "7 天正常运行时间"
  uptimeMonth: "30天的正常运行时间"
  uptimeYear: "1年的正常运行时间"
  liveStatusHtmlComment: "<!--实时状态-->"
  degradedPerformance: "🟨 加载速度慢"
  completeOutage: "🟥 所有网站均离线"
  partialOutage: "🟧 部分网站离线"
